### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol(InvalidHeader("sec-websocket-key"))',

### ISSUE THREAD

**Issue by lucasjinreal** [rookie0/rains#5]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol(InvalidHeader("sec-websocket-key"))',

tried your code build myself, got above errors.

**Comment by lucasjinreal** [comment]
cargo install rains  没有问题，
自己编译main 源代码报错！！！！！！！！！！

**Comment by rookie0** [comment]
#4
