### ISSUE TITLE
UNstable build

### ISSUE THREAD

**Issue by lucasjinreal** [rookie0/rains#6]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/21303438/218234476-3002dba5-4abc-4ab0-96df-72e7140dae64.png">

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol(InvalidHeader("sec-websocket-key"))', F:\weapons\rust\rubox\vendor\rains\src\sina.rs:457:4
```

```
rustc 1.67.1
```

Can give me a reason? SOOOOO confused

**Comment by rookie0** [comment]
#4
